-- Run in Supabase SQL editor (or migration) before enabling morning brief ingestion.
-- Rows are INSERT-only from the ingestion agent (Claude); dashboard reads via anon JWT.

CREATE TABLE IF NOT EXISTS public.brief_entries (
  id bigserial PRIMARY KEY,
  generated_at timestamptz NOT NULL DEFAULT now(),
  executive_summary text,
  watch_list text,
  book_touchpoints text,
  raw_response text,
  physical_premium_score numeric,
  wind_gw numeric,
  ttf_eur_mwh numeric,
  market_price_gbp_mwh numeric,
  source text NOT NULL DEFAULT 'Claude claude-sonnet-4-20250514'
);

COMMENT ON TABLE public.brief_entries IS
  'AI morning brief; generated by python-agents/ingestion-agent/main.py';

CREATE INDEX IF NOT EXISTS brief_entries_generated_at_idx
  ON public.brief_entries (generated_at DESC);

ALTER TABLE public.brief_entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anon read brief_entries"
  ON public.brief_entries
  FOR SELECT
  TO anon
  USING (true);

CREATE POLICY "Allow authenticated read brief_entries"
  ON public.brief_entries
  FOR SELECT
  TO authenticated
  USING (true);

GRANT SELECT ON public.brief_entries TO anon;
GRANT SELECT ON public.brief_entries TO authenticated;
